version: '3.3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - network_project

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - network_project
    depends_on:
      - mariadb    

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    env_file: .env
    volumes:
      - wp:/var/www/html
    networks:
      - network_project
    depends_on:
      - wordpress
    ports:
      - "443:443"

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/saltmer/data/db

  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/saltmer/data/wp

networks:
  network_project:
    driver: bridge  
    
