version: '3.7'

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/saltmer/data/db

  wp:
    name: wp
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/saltmer/data/wp

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - network_project

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wp:/var/www/html
    networks:
      - network_project
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    restart: always
    env_file: .env
    volumes:
      - wp:/var/www/html
    networks:
      - network_project
    depends_on:
      - wordpress
    ports:
      - "443:443"

networks:
  network_project:
    name: network_project
    driver: bridge  
    
